<?php
require('view/header.phtml');
require_once('model/account.php');

if (isset($_SESSION['login']))
{
    ?>
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Purchase Complete!</h4>
        <p>Thank you for your purchase, your order is currently being processed and will arrive at your door ASAP!</p>
        <hr>
        <p class="mb-0">Click here to <a href="index.php">Continue Shopping</a> or <a href="orderHistory.php">View your Order</a> </p>
    </div>
<?php

}
else{
    ?>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>You cannot view this page at this time :(</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

<?php

}
?>



<?php
require ('view/footer.phtml'); ?>
