<!-- Footer -->
<div>
</div>
<div id="footerDiv" ></div>
<footer class="footer text-center bg-dark">
    <div class="container">
        <span class="text-light">Copyright © 2021 Joota</span>
    </div>
</footer>
<!-- Footer -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/js/jquery-3.4.1.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
