<?php
require_once('model/account.php');
require_once('model/products.php');


session_start();

$user = new account();

if (isset($_GET['logout']) && $_GET['logout'] == true)
{
    $user ->logout();
}

?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Juta</title>

<!--    <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">-->
<!--    <link rel="stylesheet" href="Stylesheet.css">-->
    <script src="https://kit.fontawesome.com/f687ca6f88.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../flickity/flickity.css">
    <script src="../flickity/flickity.pkgd.min.js"></script>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles -->
    <link href="/css/my-style.css" rel="stylesheet">

<!--    <script src="../flickity/flickity.pkgd.min.js"></script>-->
</head>

<body>
<div style="background-color: #0d0d0d;" class="text-light" role="alert">
   <center> <strong>Free Worldwide Shipping</strong></center>
</div>

<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #f5fffa ;">
    <a class="navbar-brand" href="../index.php"><img src="../logo.png" ></a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul style="padding-left:3%" class="navbar-nav mr-auto">
            <li class="pri" >
                <div class="dropdown" >
                    <button style="background-color: #f5fffa" class="dropbtn"><h5 style="color: #1a1110">Men</h5></button>
                    <div class="dropdown-content" style="background-color: #f5fffa">
                        <?php
                        $subCategory = new products();
                        $menSubCategory = $subCategory->getSubCategories("Men");
                                            $allShoes = 0;
                                            $n = $menSubCategory->rowCount();

                                            for ($i=0; $i<$n; $i++)
                                            {
                                                $result = $menSubCategory->fetch(PDO::FETCH_ASSOC);
                                                $cat = $result['category'];
                                                $subCat = $result['subCategory'];
                                                $catId = $result['categoryId'];
                                                if($allShoes == 0){
                                                    $allShoes++;
                        ?>
                        <a href="products.php?catId=&cat=<?php echo "Men" . "&subCat=allShoes&sortBy=" ?>"><strong><?php echo "All Shoes" ?></strong></a>
                                                <?php } ?>
                        <a href="products.php?catId=<?php echo $catId ?>&cat=<?php echo $cat?>&subCat=<?php echo $subCat."&sortBy="  ?>"><strong><?php echo $subCat ?></strong></a>
                                            <?php }?>

                    </div>
                </div>
            </li>
            <li>
                <div class="dropdown">
                    <button style="background-color: #f5fffa" class="dropbtn"><h5 style="color: #1a1110">Women</h5></button>
                    <div class="dropdown-content" style="background-color: #f5fffa">
                        <?php
//                        $subCategory = new navbar();
                        $womenSubCategory = $subCategory->getSubCategories("Women");
                        $allShoes = 0;
                        $n = $womenSubCategory->rowCount();

                        for ($i=0; $i<$n; $i++)
                        {
                        $result = $womenSubCategory->fetch(PDO::FETCH_ASSOC);
                        $cat = $result['category'];
                        $subCat = $result['subCategory'];
                        $catId = $result['categoryId'];
                        if($allShoes == 0){
                        $allShoes++;
                        ?>
                        <a href="products.php?catId=&cat=<?php echo $cat . "&subCat=allShoes&sortBy="  ?>"><strong><?php echo "All Shoes" ?></strong></a>
                                                <?php } ?>
                        <a href="products.php?catId=<?php echo $catId ?>&subCat=<?php echo $subCat?>&cat=<?php echo $cat."&sortBy="  ?>"><strong><?php echo $subCat ?></strong></a>
                                            <?php } ?>
                    </div>
                </div>
            </li>
            <li>
                <div class="dropdown">
                    <button style="background-color: #f5fffa" class="dropbtn"><h5 style="color: #1a1110">Boys</h5></button>
                    <div class="dropdown-content" style="background-color: #f5fffa">
                        <?php
                        $boysSubCategory = $subCategory->getSubCategories("Boys");
                        $allShoes = 0;
                        $n = $boysSubCategory->rowCount();

                        for ($i=0; $i<$n; $i++)
                        {
                        $result = $boysSubCategory->fetch(PDO::FETCH_ASSOC);
                        $cat = $result['category'];
                        $subCat = $result['subCategory'];
                        $catId = $result['categoryId'];
                        if($allShoes == 0){
                        $allShoes++;
                        ?>
                        <a href="products.php?catId=&subCat=<?php echo "allShoes" . "&cat=". $cat."&sortBy="  ?>"><strong><?php echo "All Shoes" ?></strong></a>
                                                <?php } ?>
                        <a href="products.php?catId=<?php echo $catId ?>&subCat=<?php echo $subCat?>&cat=<?php echo $cat ."&sortBy=" ?>"><strong><?php echo $subCat ?></strong></a>
                                            <?php } ?>
                    </div>
                </div>
            </li>
            <li>
                <div class="dropdown">
                    <button style="background-color: #f5fffa" class="dropbtn"><h5 style="color: #1a1110">Girls</h5></button>
                    <div class="dropdown-content" style="background-color: #f5fffa">
                        <?php
                        $girlsSubCategory = $subCategory->getSubCategories("Girls");
                        $allShoes = 0;
                        $n = $girlsSubCategory->rowCount();

                        for ($i=0; $i<$n; $i++)
                        {
                        $result = $girlsSubCategory->fetch(PDO::FETCH_ASSOC);
                        $cat = $result['category'];
                        $subCat = $result['subCategory'];
                        $catId = $result['categoryId'];
                        if($allShoes == 0){
                        $allShoes++;
                        ?>
                        <a href="products.php?catId=&subCat=<?php echo "allShoes" . "&cat=". $cat ."&sortBy=" ?>"><strong><?php echo "All Shoes" ?></strong></a>
                                                <?php } ?>
                        <a href="products.php?catId=<?php echo $catId ?>&subCat=<?php echo $subCat?>&cat=<?php echo $cat."&sortBy="  ?>"><strong><?php echo $subCat ?></strong></a>
                                            <?php } ?>
                    </div>
                </div>
            </li>
        </ul>

        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<!--        <link rel="stylesheet" href="/resources/demos/style.css">-->
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


        <form class="form-inline" style="margin-right: 1%" action="search.php">
            <input class="form-control form-control-sm mr-3 w-75" type="text" placeholder="Search" aria-label="Search">
            <i class="fas fa-search" aria-hidden="true"></i>
        </form>

        <ul class="nav navbar-nav navbar-right ">
            <?php if(!isset($_SESSION['login'])){ ?>
                <li>
                    <a class="nav-link" href="../login.php"><h5><i class="fa fa-user-circle-o"></i>&nbsp;Login/Register</h5><span class="sr-only">(current)</span></a>
                </li>
            <?php } ?>

            <?php if(isset($_SESSION['login'])){ ?>

                <li>
                    <a class="nav-link" href="?logout==true""><h5><i class="fa fa-sign-out"></i>Log Out</h5><span class="sr-only">(current)</span></a>
                </li>
                <?php if($_SESSION['login'] == 'admin'){
                    ?>
                    <li>
                        <a class="nav-link" href=""><h5><i class="fas fa-user-shield fa-fw"></i>Admin</h5><span class="sr-only">(current)</span></a>
                    </li>
                    <?php
                }else{
                    ?>
                    <li>
                        <a class="nav-link" href="orderHistory.php"><h5><i class="fa fa-history"></i> Order History</h5><span class="sr-only">(current)</span></a>
                    </li>

                    <?php echo '<pre>';
                    //var_dump($_SESSION);
                    echo '</pre>'; }} ?>
            <li>
                <a class="nav-link" href="../basketView.php"><h5><i class="fa fa-shopping-bag"></i>&nbsp;Basket <span class="badge badge-danger"><?php if(isset($_SESSION['login'])){echo count($_SESSION['basketProds']); } ?></span></h5></a>
            </li>
            <ul class="nav navbar-nav navbar-right ">
    </div>
</nav>

</body>
