<?php require ('view/header.phtml');
//require ('model/navbar.php');
?>

    <?php if (isset($_SESSION['login']))
    {?>

       <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Welcome <?php echo $_SESSION['login']?>!</strong> You are signed in.
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <?php }?>

<div class="carousel h-50" data-flickity='{ "autoPlay": true, "wrapAround": true}'>

    <div class="carousel-cell">
        <img id="image" src="../slideshow/7.webp" class="carousel-cell-image" alt="...">
    </div>
    <div class="carousel-cell">
        <img id="image" src="../slideshow/2.webp" class="carousel-cell-image" alt="...">
    </div>
    <div class="carousel-cell">
        <img id="image" src="../slideshow/3.webp"  class="carousel-cell-image" alt="...">
    </div>
    <div class="carousel-cell">
        <img id="image" src="../slideshow/6.webp"  class="carousel-cell-image" alt="...">
    </div>
    <div class="carousel-cell">
        <img id="image" src="../slideshow/4.webp"  class="carousel-cell-image" alt="...">
    </div>
    <div class="carousel-cell">
        <img id="image" src="../slideshow/5.webp"  class="carousel-cell-image" alt="...">
    </div>


</div>
<br>
<br>
<hr>
<div class="container">
    <h3>New Arrivals</h3>
    <div class="card-columns">
        <div class="row" style="padding-right: 6%">

    <?php
    $products = new products();
    $newArrivals = $products->getNewArrivals();
    $n = $newArrivals->rowCount();

    for ($i=0; $i<$n; $i++)
    {
    $result = $newArrivals->fetch(PDO::FETCH_ASSOC);

    $prodId = $result['productId'];
    $catId = $result['categoryId'];
    $prodImg = $result['productImage'];
    $prodTitle = $result['productTitle'];
    $prodSubtitle = $result['productSubtitle'];
    $prodSubtitle = substr($prodSubtitle,0,7) . "...";
    $prodDescription = $result['productDescription'];
    $prodDescription = substr($prodDescription,0,50) . "...";
    $prodPrice = $result['Price'];
    ?>
    <div class="card" style=""  >
        <a href="../productView.php?productId=<?php echo $prodId ?>&categoryId=<?php echo $catId ?>">
            <img src="../<?php echo $prodImg  ?>1.webp" class="card-img-top" alt="...">
        </a>
        <div class="card-body" >
            <a href="../productView.php?productId=<?php echo $prodId ?>&categoryId=<?php echo $catId ?>">
                <h5 class="card-title"><?php echo $prodTitle . " " . $prodSubtitle ?></h5>
            </a>
            <h5 class="card-title"><?php echo "£" . $prodPrice ?></h5>
            <p class="card-text" id="cardheight"><?php echo $prodDescription ?></p>
            <a href="../productView.php?productId=<?php echo $prodId ?>&categoryId=<?php echo $catId ?>" class="btn btn-outline-primary btn-block">View</a>
        </div>
    </div>
    <?php
    }
    ?>
</div>
    </div>
</div>

<?php require('view/footer.phtml');?>
