<?php
require('view/header.phtml');
require_once('model/account.php');

if (isset($_POST['login']))

{
    $name = $_POST['uname'];
    $pass = $_POST['password'];
    $email = $_POST['uname'];
    $user = new account();
    $user->login($name, $pass, $email);
}
?>
<hr>
    <div class="container text-center ">
        <div class="row justify-content-center" >
            <div class="col-xs-12">
                <form method="post">
                 <h2>Login</h2><hr>
                <input type="text" name="uname" class="form-control" placeholder="Username" required autofocus>
                <br>
                <input type="password" name="password" class="form-control" placeholder="Password" required>
                <br>
                <button class="btn btn-outline-info btn-block" type="submit" name="login">Log In</button>
                <br>
                <p class="lead">Not a member yet? <a href="/register.php">Register here</a></p>
                </form>
            </div>
        </div>
    </div>

<?php
require ('view/footer.phtml'); ?>
