<?php
require('view/header.phtml');
require_once('model/account.php');

if (isset($_POST['register'])) {
    $username = $_POST['username'];
    $pass = $_POST['password'];
    $email = $_POST['email'];
    $phone = $_POST['phone'];
    $fName = $_POST['firstName'];
    $lName = $_POST['lastName'];
    $addr1 = $_POST['addr1'];
    $addr2 = $_POST['addr2'];
    $city = $_POST['city'];
    $postcode = $_POST['postcode'];

    $user = new account();
    $user->register($username, $pass, $email, $fName, $lName, $phone, $addr1, $addr2, $city, $postcode);
}
?>

    <hr>
    <div class="container text-center ">


        <div class="row justify-content-center" >

            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                <form method="post">
                    <h2>Register here</h2>
                    <hr>
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <input type="text" name="username" id="username" class="form-control input-lg" placeholder="Username" tabindex="1" required>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <input type="password" name="password" id="password" class="form-control input-lg" placeholder="Password" tabindex="2" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <input type="email" name="email" id="email" class="form-control input-lg" placeholder="Email" tabindex="3" required>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <input type="number" name="phone" id="phone" class="form-control input-lg" placeholder="Phone No" tabindex="3" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <input type="text" name="firstName" id="firstName" class="form-control input-lg" placeholder="First Name" tabindex="5" required>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <input type="text" name="lastName" id="lastName" class="form-control input-lg" placeholder="Last Name" tabindex="6" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <input type="text" name="addr1" id="addr1" class="form-control input-lg" placeholder="Address i.e. 64 Burton Street" tabindex="5" required>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <input type="text" name="addr2" id="addr2" class="form-control input-lg" placeholder="Address Line 2 (optional)" tabindex="6">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <input type="text" name="city" id="city" class="form-control input-lg" placeholder="City" tabindex="5" required>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <input type="text" name="postcode" id="postcode" class="form-control input-lg" placeholder="Postcode" tabindex="6" required>
                            </div>
                        </div>
                    </div>


                    <hr>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <input type="submit" name="register" value="Register" class="btn btn-dark btn-block btn-lg" tabindex="7">
                        </div>
                        <div class="form-group col-md-6">
                            <p class="lead">Already a member? <a href="/login.php">Log in</a></p>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

<?php
require ('view/footer.phtml');
?>
